/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.bmuskalla.junit5.christmas.decoration;

import org.junit.jupiter.api.*;

import java.util.Arrays;
import java.util.Iterator;
import java.util.stream.Stream;

@DisplayNameGeneration(JUnitChristmasDecorations.class)
class DecorationsTest {
    
    @TestFactory
    Stream<DynamicTest> generateTestsFromLyrics() {
        String lyrics = "Silent night, holy night\n" +
                "All is calm, all is bright\n" +
                "'Round yon virgin Mother and Child\n" +
                "Holy infant so tender and mild\n" +
                "Sleep in heavenly peace\n" +
                "Sleep in heavenly peace\n" +
                "Silent night, holy night!\n" +
                "Shepherds quake at the sight!\n" +
                "Glories stream from heaven afar;\n" +
                "Heavenly hosts sing Al-le-lu-ia!";
        final Iterator<String> testLines = Arrays.stream(lyrics.split("\\n")).iterator();
        final JUnitChristmasDecorations decorations = new JUnitChristmasDecorations();
        return DynamicTest.stream(testLines, decorations::decorate, input -> {
        });
    }

}
